"""init

Revision ID: 087bea0b925d
Revises: 6f670129242a
Create Date: 2025-03-01 20:58:25.495165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087bea0b925d'
down_revision: Union[str, None] = '6f670129242a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_name2_key', 'tags', type_='unique')
    op.drop_column('tags', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('tags_name2_key', 'tags', ['name2'])
    # ### end Alembic commands ###
