"""init

Revision ID: 174a867d21f0
Revises: f914097d5cbd
Create Date: 2025-04-01 16:42:05.369825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174a867d21f0'
down_revision: Union[str, None] = 'f914097d5cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_board', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'selected_board')
    # ### end Alembic commands ###
