"""init

Revision ID: 2792accccc37
Revises: c922de396e30
Create Date: 2025-04-07 06:27:56.475848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2792accccc37'
down_revision: Union[str, None] = 'c922de396e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('updates_comment_id_fkey', 'updates', type_='foreignkey')
    op.create_foreign_key(None, 'updates', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.create_foreign_key('updates_comment_id_fkey', 'updates', 'pins', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
