"""init

Revision ID: 292fd5340600
Revises: b788a77be1a1
Create Date: 2024-12-20 14:49:18.472454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292fd5340600'
down_revision: Union[str, None] = 'b788a77be1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('image', sa.String(length=200), nullable=True))
    op.drop_column('pins', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('file', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('pins', 'image')
    # ### end Alembic commands ###
