"""init

Revision ID: 425225506f9a
Revises: a34f4cdfcb18
Create Date: 2025-04-04 07:30:31.195343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425225506f9a'
down_revision: Union[str, None] = 'a34f4cdfcb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('content', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'content')
    # ### end Alembic commands ###
