"""init

Revision ID: 47a5ada58c87
Revises: 7bdfeb1a2207
Create Date: 2025-04-03 06:49:56.985949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a5ada58c87'
down_revision: Union[str, None] = '7bdfeb1a2207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users_view_pins', sa.Column('update_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_view_pins', 'updates', ['update_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_view_pins', type_='foreignkey')
    op.drop_column('users_view_pins', 'update_id')
    op.drop_table('updates')
    # ### end Alembic commands ###
