"""init

Revision ID: 4979d3902f42
Revises: fe7b2b76951e
Create Date: 2025-04-03 07:16:17.764977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4979d3902f42'
down_revision: Union[str, None] = 'fe7b2b76951e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_recommendations_pins', 'update_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_recommendations_pins', 'update_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
