"""init

Revision ID: 6b71cd21916c
Revises: 2792accccc37
Create Date: 2025-04-08 01:30:56.589415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b71cd21916c'
down_revision: Union[str, None] = '2792accccc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'updates', 'comments', ['reply_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.drop_column('updates', 'reply_id')
    # ### end Alembic commands ###
