"""init

Revision ID: 6f670129242a
Revises: c8eee77e7ec9
Create Date: 2025-03-01 20:54:15.640602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f670129242a'
down_revision: Union[str, None] = 'c8eee77e7ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name2', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'tags', ['name2'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'name2')
    # ### end Alembic commands ###
