"""init

Revision ID: 728da9e7a7da
Revises: 14d5c650b029
Create Date: 2024-12-20 11:26:59.156234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728da9e7a7da'
down_revision: Union[str, None] = '14d5c650b029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_pin_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'pin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('pin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tags_pin_id_fkey', 'tags', 'pins', ['pin_id'], ['id'])
    # ### end Alembic commands ###
