"""init

Revision ID: 98b604385285
Revises: 4979d3902f42
Create Date: 2025-04-03 07:31:44.351003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b604385285'
down_revision: Union[str, None] = '4979d3902f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_recommendations_pins', 'update_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_recommendations_pins', 'update_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
