"""init

Revision ID: 9a3359ac41b9
Revises: a755c16acd03
Create Date: 2025-04-05 04:05:52.694568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3359ac41b9'
down_revision: Union[str, None] = 'a755c16acd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('ids_list', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('updates', 'uri_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('uri_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('updates', 'ids_list')
    # ### end Alembic commands ###
