"""init

Revision ID: 9fa7713746df
Revises: 9b37dd31f75c
Create Date: 2025-04-01 18:36:14.008684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa7713746df'
down_revision: Union[str, None] = '9b37dd31f75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('board_pins_pin_id_fkey', 'board_pins', type_='foreignkey')
    op.drop_constraint('board_pins_board_id_fkey', 'board_pins', type_='foreignkey')
    op.create_foreign_key(None, 'board_pins', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'board_pins', 'pins', ['pin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_pins', type_='foreignkey')
    op.drop_constraint(None, 'board_pins', type_='foreignkey')
    op.create_foreign_key('board_pins_board_id_fkey', 'board_pins', 'boards', ['board_id'], ['id'])
    op.create_foreign_key('board_pins_pin_id_fkey', 'board_pins', 'pins', ['pin_id'], ['id'])
    # ### end Alembic commands ###
