"""init

Revision ID: a7db4c11dd37
Revises: e29bf9954e2b
Create Date: 2025-01-14 04:18:17.010777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7db4c11dd37'
down_revision: Union[str, None] = 'e29bf9954e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('tiktok', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('telegram', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('pinterest', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pinterest')
    op.drop_column('users', 'telegram')
    op.drop_column('users', 'tiktok')
    op.drop_column('users', 'instagram')
    # ### end Alembic commands ###
