"""users selected board column

Revision ID: c1b7e54cb920
Revises: cd0d6e33bb27
Create Date: 2025-04-14 18:18:01.178056

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1b7e54cb920"
down_revision: Union[str, None] = "cd0d6e33bb27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("selected_board", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "boards", ["selected_board"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "selected_board")
    # ### end Alembic commands ###
