"""init

Revision ID: c8801af6dbe9
Revises: daef0140de50
Create Date: 2025-04-07 05:19:51.968726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8801af6dbe9'
down_revision: Union[str, None] = 'daef0140de50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('pin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'updates', 'pins', ['pin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.drop_column('updates', 'pin_id')
    # ### end Alembic commands ###
