"""init

Revision ID: c8eee77e7ec9
Revises: 9e56e7695b88
Create Date: 2025-03-01 01:43:57.092688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8eee77e7ec9'
down_revision: Union[str, None] = '9e56e7695b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_name2_key', 'tags', type_='unique')
    op.drop_column('tags', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('tags_name2_key', 'tags', ['name2'])
    # ### end Alembic commands ###
