"""init

Revision ID: c922de396e30
Revises: c8801af6dbe9
Create Date: 2025-04-07 06:14:48.595786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c922de396e30'
down_revision: Union[str, None] = 'c8801af6dbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'updates', 'pins', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.drop_column('updates', 'comment_id')
    # ### end Alembic commands ###
