"""add_named_foreign_keys_to_users_and_boards

Revision ID: d948933f5835
Revises: 2f669393d5f6
Create Date: 2025-04-15 10:49:36.415780

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d948933f5835"
down_revision: Union[str, None] = "2f669393d5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
