"""init

Revision ID: daef0140de50
Revises: 83e35dbc9276
Create Date: 2025-04-07 05:05:54.169262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daef0140de50'
down_revision: Union[str, None] = '83e35dbc9276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('user_update_to_id', sa.Integer(), nullable=False))
    op.alter_column('updates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'updates', 'users', ['user_update_to_id'], ['id'])
    op.drop_column('updates', 'ids_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('ids_list', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.alter_column('updates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('updates', 'user_update_to_id')
    # ### end Alembic commands ###
