"""init

Revision ID: de5f1b81b8e0
Revises: 98b604385285
Create Date: 2025-04-03 07:40:25.426896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5f1b81b8e0'
down_revision: Union[str, None] = '98b604385285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_recommendations_pins', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_recommendations_pins', 'id')
    # ### end Alembic commands ###
