"""init

Revision ID: f7c225088ee5
Revises: 11a1166a9bef
Create Date: 2025-01-14 02:53:30.601852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c225088ee5'
down_revision: Union[str, None] = '11a1166a9bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_image')
    # ### end Alembic commands ###
