"""init

Revision ID: fb4bb5258e24
Revises: 425225506f9a
Create Date: 2025-04-04 23:15:53.020746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4bb5258e24'
down_revision: Union[str, None] = '425225506f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('update_type', sa.Enum('RECOMMENDATIONS', 'FOLLOW', 'LIKE_PIN', 'SAVE_PIN', 'COMMENT_PIN', 'LIKE_COMMENT', 'REPLY_COMMENT', name='update_type_enum'), nullable=False))
    op.add_column('updates', sa.Column('uri_list', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'uri_list')
    op.drop_column('updates', 'update_type')
    # ### end Alembic commands ###
