"""init

Revision ID: fe7b2b76951e
Revises: 47a5ada58c87
Create Date: 2025-04-03 07:04:11.182101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7b2b76951e'
down_revision: Union[str, None] = '47a5ada58c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_recommendations_pins', sa.Column('update_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users_recommendations_pins', 'updates', ['update_id'], ['id'])
    op.drop_constraint('users_view_pins_update_id_fkey', 'users_view_pins', type_='foreignkey')
    op.drop_column('users_view_pins', 'update_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_view_pins', sa.Column('update_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_view_pins_update_id_fkey', 'users_view_pins', 'updates', ['update_id'], ['id'])
    op.drop_constraint(None, 'users_recommendations_pins', type_='foreignkey')
    op.drop_column('users_recommendations_pins', 'update_id')
    # ### end Alembic commands ###
