FROM node:18-alpine

# Copy package.json and package-lock.json
COPY ./vuejs/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY ./vuejs/ .

# Run the project
CMD ["npm", "run", "dev", "--", "--host"]