version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # CI_PROJECT_DIR указывает на /builds/<group>/<project> внутри DIND,
    # поэтому здесь подставляем именно его
    volumes:
      - ${CI_PROJECT_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://pint3rest.xyz/prometheus/'
      - '--web.route-prefix=/prometheus'
    networks:
      - pinterest-network






  # loki:
  #   image: grafana/loki:2.9.4
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ./loki-config.yml:/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.9.4
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config.yml:/etc/promtail/config.yml
  #     - ./logs:/logs
  #   command: -config.file=/etc/promtail/config.yml

  # grafana:
  #   image: grafana/grafana:10.2.3
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus
  #     - loki


networks:
  pinterest-network:
    external: true