FROM python:3.10

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /fastapi  

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["gunicorn", "app.main:app", "-k", "uvicorn.workers.UvicornWorker", "--workers", "4", "--bind", "0.0.0.0:8000", "--timeout", "120"]