services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://pint3rest.xyz/prometheus/'
      - '--web.route-prefix=/prometheus'
    networks:
      - pinterest-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=https://pint3rest.xyz/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - pinterest-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log/nginx/:/var/log/nginx/                        
      - ${LOGS_PATH}:/logs/fastapi
      - promtail-positions:/tmp               
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - pinterest-network


  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - loki_data:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command:
      - -config.file=/etc/loki/loki-config.yaml
    networks:
      - pinterest-network



  # loki:
  #   image: grafana/loki:2.9.4
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ./loki-config.yml:/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.9.4
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config.yml:/etc/promtail/config.yml
  #     - ./logs:/logs
  #   command: -config.file=/etc/promtail/config.yml

  # grafana:
  #   image: grafana/grafana:10.2.3
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus
  #     - loki


networks:
  pinterest-network:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  promtail-positions:
  loki_data: