
FROM node:18 AS builder
WORKDIR /app

# Копируем файлы package.json и package-lock.json (если есть) для установки зависимостей
COPY ./vuejs/package*.json ./
RUN npm install

# Копируем весь исходный код и собираем приложение
COPY ./vuejs/ .
RUN npm run build

# Этап 2: запуск через Nginx
FROM nginx:stable-alpine
# Копируем собранные файлы в директорию, обслуживаемую Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Если необходимо, можно заменить конфигурацию Nginx (опционально)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт 80 для доступа
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]