auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

frontend:
  query_timeout: 10s

limits_config:
  max_query_length: 100000
  max_query_limit: 500
  max_streams_per_query: 10000

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks