server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  chunk_idle_period: 5m
  max_chunk_age: 1h

  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory       # use in-memory ring instead of Consul
      replication_factor: 1   # единичный инстанс

limits_config:
  allow_structured_metadata: false

storage_config:
  filesystem:
    directory: /loki/chunks
  boltdb:
    directory: /loki/index

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h