server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # Здесь добавляем заголовок X-Grafana-Org-Id
    headers:
      X-Grafana-Org-Id: "1"

scrape_configs:
  - job_name: fastapi_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          __path__: /logs/fastapi/*.jsonl  # Путь к логам FastAPI

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log  # Путь к логам Nginx
