"""init

Revision ID: 1a707f0c3ace
Revises: a6bf39ddef8e
Create Date: 2025-02-10 09:02:58.077354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a707f0c3ace'
down_revision: Union[str, None] = 'a6bf39ddef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('side_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'side_open')
    # ### end Alembic commands ###
