"""init

Revision ID: 80fa7c2029cf
Revises: 1a707f0c3ace
Create Date: 2025-02-22 17:38:24.259870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fa7c2029cf'
down_revision: Union[str, None] = '1a707f0c3ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('test', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'test')
    # ### end Alembic commands ###
