"""init

Revision ID: a851c8da46ad
Revises: e84f7ca0ae35
Create Date: 2024-12-20 09:31:56.656728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a851c8da46ad'
down_revision: Union[str, None] = 'e84f7ca0ae35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pins', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pins', type_='foreignkey')
    op.drop_column('pins', 'user_id')
    # ### end Alembic commands ###
