"""init

Revision ID: b788a77be1a1
Revises: 728da9e7a7da
Create Date: 2024-12-20 14:48:48.469559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b788a77be1a1'
down_revision: Union[str, None] = '728da9e7a7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pins', sa.Column('file', sa.String(length=200), nullable=True))
    op.drop_column('pins', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('pins', 'file')
    op.drop_table('comments')
    # ### end Alembic commands ###
