"""init

Revision ID: b975dc045a71
Revises: a0d31c25c529
Create Date: 2024-12-17 21:00:21.577393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b975dc045a71'
down_revision: Union[str, None] = 'a0d31c25c529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
