"""init

Revision ID: e1149ae40da5
Revises: 72ee48499ad2
Create Date: 2025-01-30 19:37:28.781785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1149ae40da5'
down_revision: Union[str, None] = '72ee48499ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image', sa.String(length=200), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=400),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.String(length=400),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'image')
    # ### end Alembic commands ###
